### PR TITLE
fix: custom FloatingActionButton

### LINKED ISSUE #132: Error, while creating a new workout in debug-mode
I want to contribute to this project and followed the "how to get started"-instructions described in the readme-file. Im still getting this error in heroes.dart, when i. e. creating a new workout in debug-mode. When trying the same thing without debug-mode than it works perfectly. 

image

Does anyone know how to deal with that or had the same problem?

### PR DESCRIPTION
**Pull request by MhouneyLH**
# Summary
This PR fixed #132, where the heroTag-property of the FloatingActionButton caused an error. (even if it was set to null)
I created a CustomFloatingActionButton without the heroTag-property and replaced all default FloatingActionButtons.

By now the Class only have 3 members:
* Icon
* size
* Function, when tapped

floatingActionButtonNormal
floatingActionButtonWIthInkwell

### CODE REVIEW

File: lib/UI/workout/workout_page.dart [hunk 1]
```diff
@@ -80,16 +81,12 @@ class _WorkoutPageState extends State<WorkoutPage> {
...
-              color: theme.colorTheme.backgroundColorVariation,
-            ),
-            onPressed: () {
-              showAlertDialogExercise(context);
-            },
-          ),
+          floatingActionButton: CustomFloatingActionButton(
+                        icon: Icons.add,
+                        onTap: () {
+                          showAlertDialogExercise(context);
```
Comment (jorre127) [inline lib/UI/workout/workout_page.dart]: use arrow function here

File: lib/src/widgets/custom_floating_action_button.dart [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+class CustomFloatingActionButton extends StatelessWidget {
+  final IconData? icon;
+  final double? size;
+  final VoidCallback? onTap;
+
+  CustomFloatingActionButton({
+    @required this.icon,
+    this.size = 50.0,
+    @required this.onTap,
```
Comment (jorre127) [inline lib/src/widgets/custom_floating_action_button.dart]: put required params first

File: lib/src/widgets/custom_floating_action_button.dart [hunk 3]
```diff
@@ -0,0 +1,50 @@
+import 'package:exerlog/src/widgets/theme/theme_provider.dart';
+import 'package:flutter/material.dart';
+
+class CustomFloatingActionButton extends StatelessWidget {
+  final IconData? icon;
+  final double? size;
+  final VoidCallback? onTap;
+
+  CustomFloatingActionButton({
+    @required this.icon,
```
Comment (jorre127) [inline lib/src/widgets/custom_floating_action_button.dart]: should the icon be nullable if it's required?

File: lib/src/widgets/custom_floating_action_button.dart [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+    this.size = 50.0,
+    @required this.onTap,
+  });
+
+  @override
+  Widget build(BuildContext context) => ThemeProvider(
+        builder: (context, theme) => Container(
+          decoration: BoxDecoration(
+            color: theme.colorTheme.primaryColor,
+            borderRadius: BorderRadius.circular(size!),
```
Comment (jorre127) [inline lib/src/widgets/custom_floating_action_button.dart]: Seeing as you gave size a default value, you can just not make it nullable. Then you don't have to force it here

File: lib/src/widgets/custom_floating_action_button.dart (hunk 3 above)
Comment (jorre127) [reply lib/src/widgets/custom_floating_action_button.dart]: Same for onTap

**Comment by MhouneyLH** [comment]
Should I name every commit with 'feat:', 'chore', etc. or only the PR-title?

**Comment by jorre127** [comment]
> Should I name every commit with 'feat:', 'chore', etc. or only the PR-title?

Personally I don't think its necessary but I see most other PR's do name every commit, so maybe to keep it consistent you should add it.

**Review by jorre127 — APPROVED** [review]

**Comment by tenshiAMD** [comment]
> Should I name every commit with 'feat:', 'chore', etc. or only the PR-title?

@MhouneyLH yes, we need to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Review by momshaddinury — APPROVED** [review]

**Comment by KalleHallden** [comment]
@all-contributors please add @MhouneyLH for code
