### PR TITLE
patch: Fix Navigation

### LINKED ISSUE #41: Fix navigation
When finishing a workout you go to the calendar page. But the problem is that you can then navigate back using the back arrow to the workout you just finished (I assume this is not intended seeing as we already finished and saved this workout at this moment). 

Also when pressing the back button on the workout page, we do a pop and then push to the calendar screen. This looks visually confusing because we press back, but it looks like a new page gets pushed onto the screen.

My suggestion is to change the navigation flow so when you go from the calendar page to the workout page we do this with a push instead ( its a push replace now) this way we can just pop when pressing the back button. Same for when we save the session we can just pop back to the calendar page. This way we don't have the problem where we can navigate back to a already finished session.

https://user-images.githubusercontent.com/44479965/184024924-fb3f3727-8402-410a-9991-1a354e495c64.mp4

### PR DESCRIPTION
**Pull request by momshaddinury**
### Issue
- #41 
### What was done?
- Back button navigation logic fixed
- Alert dialog navigation logic fixed

Closes #41

### CODE REVIEW

File: lib/UI/prev_workout/prev_workout_page.dart [hunk 1]
```diff
@@ -81,11 +81,6 @@ class _PrevWorkoutPageState extends State<PrevWorkoutPage> {
                 leading: BackButton(
                   onPressed: () {
                     Navigator.of(context).pop();
```
Comment (jorre127) [inline lib/UI/prev_workout/prev_workout_page.dart]: you can do this now:

` onPressed: Navigator.of(context).pop,`

File: lib/UI/prev_workout/prev_workout_page.dart [hunk 2]
```diff
@@ -236,11 +234,7 @@ class _PrevWorkoutPageState extends State<PrevWorkoutPage> {
       onPressed: () {
         deleteWorkout(workoutData.workout);
         Navigator.of(context).pop();
-        Navigator.of(context).push(
-          MaterialPageRoute(
-            builder: (context) => CalendarScreen(),
-          ),
-        );
+        Navigator.of(context).pop();
```
Comment (jorre127) [inline lib/UI/prev_workout/prev_workout_page.dart]: If you want to pop the navigator twice you can do it something like this:

```
  Navigator.of(context)
    ..pop()
    ..pop();
```

File: lib/UI/workout/workout_page.dart [hunk 3]
```diff
@@ -96,11 +95,7 @@ class _WorkoutPageState extends State<WorkoutPage> {
             backgroundColor: theme.colorTheme.backgroundColorVariation,
             leading: BackButton(
               onPressed: () {
-                Navigator.of(context).pushReplacement(
-                  MaterialPageRoute(
-                    builder: (context) => CalendarScreen(),
-                  ),
-                );
+                Navigator.pop(context);
```
Comment (jorre127) [inline lib/UI/workout/workout_page.dart]: You can do:

`onPressed: () => Navigator.pop(context)` or` onPressed: Navigator.of(context).pop;`

File: lib/UI/workout/workout_page.dart [hunk 4]
```diff
@@ -267,11 +262,7 @@ class _WorkoutPageState extends State<WorkoutPage> {
       onPressed: () {
         saveWorkout(workoutData.workout);
         Navigator.of(context).pop();
-        Navigator.of(context).push(
-          MaterialPageRoute(
-            builder: (context) => CalendarScreen(),
-          ),
-        );
+        Navigator.of(context).pop();
```
Comment (jorre127) [inline lib/UI/workout/workout_page.dart]: Same as a previous comment, you can use .. when calling a method on the same reference twice.

**Review by jorre127 — APPROVED** [review]
